language: php

dist: trusty

env:
  global:
    - COMPOSER_ROOT_VERSION=1.x-dev

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL INSTALLER_VERSION=1.0.x-dev
    - php: 7.0
      env: DB=PGSQL INSTALLER_VERSION=1.1.x-dev
    - php: 7.1
      env: DB=MYSQL INSTALLER_VERSION=1.2.x-dev
    - php: 7.2
      env: DB=MYSQL INSTALLER_VERSION=1.x-dev

before_script:
  # Init PHP & increase speed by removing xdebug
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  # Install composer dependencies
  - composer validate
  - composer require --no-update silverstripe/installer "$INSTALLER_VERSION"
  - if [[ "$DB" == "PGSQL" ]]; then composer require --no-update silverstripe/postgresql:2.0.x-dev; fi
  - composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

  # Validate cow schema
  - composer global require silverstripe/cow ^2
  - ~/.composer/vendor/bin/cow schema:validate

script:
  - vendor/bin/phpunit --testsuite recipe-blog
